name: flutte_django
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0          # Para solicitudes HTTP (login, registro, etc.)
  web_socket_channel: ^3.0.3  # Para gestionar WebSockets
  intl: ^0.20.2         # Para formatear fechas y números
  flutter_blur: ^0.0.2
  google_fonts: ^6.2.1
  animate_do: ^3.0.1
  timezone: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

 
